apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gse-buildah-task
spec:
  params:
    - name: BUILDER_IMAGE
      description: The location of the buildah builder image.
      default: quay.io/buildah/stable:v1.11.0
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: Path to the directory to use as context.
      default: .
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "false"
    - name: docker-image
      type: string
  steps:
    - name: build
      image: $(params.BUILDER_IMAGE)
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: $(workspaces.output.path)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          SHORT_GIT_HASH=$(cat .git/FETCH_HEAD | awk '{print substr($1,0,7)}')
          echo "SHORT_GIT_HASH = $SHORT_GIT_HASH"
          echo Building Image $(params.docker-image):$SHORT_GIT_HASH
          echo -----------------------------------
          echo Copying git source to /workspace/output/
          cp -R /workspace/source /workspace/output/
          echo -----------------------------------
          buildah bud --tls-verify=$(params.TLSVERIFY) --layers -f $(params.DOCKERFILE) -t $(params.docker-image):$SHORT_GIT_HASH $(params.CONTEXT)
          echo Pushing Image $(params.docker-image):$SHORT_GIT_HASH
          buildah push --tls-verify=$(params.TLSVERIFY) $(params.docker-image):$SHORT_GIT_HASH docker://$(params.docker-image):$SHORT_GIT_HASH
      securityContext:
        privileged: true
  volumes:
    - emptyDir: {}
      name: varlibcontainers
